[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
  -D CORE_DEBUG_LEVEL=1
lib_deps =
  https://github.com/Sensirion/arduino-i2c-scd4x.git
  https://github.com/adafruit/Adafruit-GFX-Library.git
  https://github.com/adafruit/Adafruit_SSD1306.git
